[tool.pytest.ini_options]
addopts = "-v -s -l -rfEX --durations=10 --alluredir=allure-results"
markers = [
    "web: Помечает тест как веб",
    "api: Помечает тест как api",
    "regression: Помечает регрессионные тесты",
    "smoke: Помечает критические тесты",
    "slow: Помечает медленные тесты",
    "fast: Помечает быстрые тесты"
]